- name: Create table markdown for containers.
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create table with items templated in containers-table file.
      lineinfile:
        path: containers-table
        regexp: 'ANYTHING'
        line: >-
          | [geerlingguy/{{ item.name }}](https://hub.docker.com/r/geerlingguy/{{ item.name }}/) | [![Build](https://github.com/geerlingguy/{{ item.name }}/actions/workflows/build.yml/badge.svg)](https://github.com/geerlingguy/{{ item.name }}/actions/workflows/build.yml) | &#10003; | [GitHub](https://github.com/geerlingguy/{{ item.name }}) |
        create: yes
        insertafter: eof
      with_items: "{{ geerlingguy_test_containers }}"

  vars:
    build_system_default: travis-ci.org
    geerlingguy_test_containers:
      - name: docker-ubuntu2404-ansible
      - name: docker-ubuntu2204-ansible
      - name: docker-ubuntu2004-ansible
      - name: docker-rockylinux9-ansible
      - name: docker-rockylinux8-ansible
      - name: docker-debian12-ansible
      - name: docker-debian11-ansible
      - name: docker-amazonlinux2023-ansible
      - name: docker-fedora41-ansible
      - name: docker-fedora40-ansible
      - name: docker-fedora39-ansible
